class PyxError(Exception):
    pass

class TaskError(Exception):
    pass
